### PR TITLE
Bifurcated into client and server repos

### PR DESCRIPTION
**Pull request by SamuelMarks**
WiP, PR is RFC

https://github.com/TerminalPres/WebSSH2-client

EDIT: For TypeScript rewrite, see: https://github.com/TerminalPres/WebSSH2-server/tree/typescript

### CODE REVIEW

**Comment by billchurch** [comment]
I like where you're going with this. Give me some time to review everything and pull the split-out client.

**Comment by billchurch** [comment]
Okay, so it seems that what is remaining is tying in the WebSSH2-client into the server-side. Ultimately what is your vision for end architecture here?

**Comment by colthreepv** [comment]
like this PR, especially the typescript version, for future-proofing

static checking also helps

**Comment by billchurch** [comment]
i want to do this but it will be in a different way. tracking in #155

**Comment by SamuelMarks** [comment]
Did you want a TypeScript version?

**Comment by billchurch** [comment]
I’d actually love that. Looking at how to refactor everything, at one point, to typescript but for now rebuilding the client in typescript should be pretty easy. Trying to decide if I want a sub module or something else. Ideally it should probably be it’s own npm module if we want to do it right.

**Pull request closed without merging**
